# name: Create Release

# on:
#   push:
#     tags:
#       - 'v*'  # Trigger the workflow on version tag push (e.g., v1.0.0)
#     branches:
#       - main

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js (if you're building a Node.js app)
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       - name: Install dependencies (if needed)
#         run: npm install

#       - name: Build the application
#         run: npm run build  # This should generate your /dist folder

#       - name: Create GitHub Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           draft: false
#           prerelease: false
          
#       - name: Upload Release Assets
#         uses: actions/upload-release-asset@v1
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./dist/*.exe
#           asset_name: Sony Bravia Remote Control Setup 1.0.0.exe
#           asset_content_type: application/zip

name: Build/Release Electron App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        uses: x6Pnda/action-electron-compiler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: Release ${{ github.ref_name }}



