name: Build/Release Electron App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        uses: x6Pnda/action-electron-compiler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: Release ${{ github.ref_name }}



